### ISSUE TITLE
ci step to automatically publish on master merge

### ISSUE THREAD

**Issue by srijan02420** [dream11/kong-host-interpolate-by-header#14]
- [ ] check if branch is rebased with master/other_branch on pr
- [ ] publish on github as release on master merge using release draft action
- [ ] publish on luarocks on master merge using release draft action
- [ ] increment version with prepare for next release
- [ ] automerge using label use https://github.com/pascalgn/automerge-action

**Comment by chirag-d11** [comment]
@srijan02420 Branch Rebasing and Automerge actions skipped since Merge policy is highly subjective and depends on use case. Will publish general guidelines on what procedure to follow.
