### ISSUE TITLE
Unable to use header value for host, getting no host allowed while connecting to upstream

### ISSUE THREAD

**Issue by Gomer05** [dream11/kong-host-interpolate-by-header#52]
### Summary

Testing the use of this plugin to send requests to different environments based on the header value fails with "failed to set the current peer, no host allowed while connecting to upstream.

### Steps To Reproduce

1. Create service:` curl  -i -X POST http://127.0.01:8001/services --data name=servicea --data url='http://192.168.7.10:8480'`
2. Create a route to servicea: `curl  -i -X POST http://127.0.0.1:8001/services/servicea/routes --data 'paths[]=/servicea' --data 'name=servicea' --data 'protocols=http' `
3. Create the plugin to route on header: `curl -i -X POST http://127.0.0.1:8001/services/servicea/plugins --data "name=host-interpolate-by-header" --data "config.fallback_host=192.168.7.10:8480" --data "config.headers=Test-Upstream" --data "config.host=www.<Test-Upstream>.com"`
4. Curl without the header works as expected and I get the response from the fallback_host
5. Curl with the header like: `curl http://127.0.0.1:8000/servicea -H "Test-Upstream: redhat"`
I get the following error in the logs, I would have expected it serve the RedHat website.
[`error] 42#0: *8502 [lua] init.lua:1085: balancer(): failed to set the current peer (address: www.redhat.com port: 80): no host allowed while connecting to upstream, client: 192.168.x.x, server: kong, request: "GET /servicea HTTP/1.1", host: "192.168.7.10:8000"`

### Additional Details & Logs

- Kong version (`2.5.1`)

If I create the plugin and pass an IP address it works
This works, but is obviously hard coded:
```
curl -i -X POST http://127.0.0.1:8001/services/servicea/plugins \
--data "name=host-interpolate-by-header"  \
--data "config.fallback_host=192.168.7.10:8480" \
--data "config.headers=Test-Upstream" \
--data "config.host=192.168.7.1"
```

But if I use a hostname hardcoded it fails to
```
curl -i -X POST http://127.0.0.1:8001/services/servicea/plugins \
--data "name=host-interpolate-by-header"  \
--data "config.fallback_host=192.168.7.10:8480" \
--data "config.headers=Loyalty-Upstream" \
--data "config.host=www.redhat.com"
```

Tried by putting the plugin on a route or a service, same results.

**Comment by Gomer05** [comment]
Tested with v1.3.0 and v1.2.1 of the plugin
Debug log:
```
2021/11/18 03:45:23 [debug] 43#0: *201 [kong] handler.lua:65 [host-interpolate-by-header] Final value of hostname is: redhat.com
2021/11/18 03:45:23 [debug] 43#0: *201 [lua] init.lua:1081: balancer(): setting address (try 1): redhat.com:80
 2021/11/18 03:45:23 [error] 43#0: *201 [lua] init.lua:1085: balancer(): failed to set the current peer (address: redhat.com port: 80): no host allowed while connecting to upstream, client: 192.168.7.238, server: kong, request: "GET /servicea HTTP/1.1", host: "192.168.7.10:8000"
 192.168.7.238 - - [18/Nov/2021:03:45:23 +0000] "GET /servicea HTTP/1.1" 500 46 "-" "curl/7.64.1"
```

Get the same error with falback_host if setting a hostname.  IP address works.

Note that this is a docker container from Kong on Docker Hub.
I have tried the same steps on both Linux and MacOS using docker and get the same result.

**Comment by Gomer05** [comment]
I have found the issue.
It seems that if the underlying service has a host based on IP address: `curl -i -X POST http://127.0.01:8001/services --data name=servicea --data url='http://192.168.7.10:8480'`
I get the error reported from the plugin. 
The service does work if the plugin is disabled though.

If I update or create the service and use a hostname like: `curl -i -X POST http://127.0.01:8001/services --data name=servicea --data url='http://www.tesla.com'`
The plugin works as expected.

So the issue seems to be in the interaction with Kong and the plugin.  Kong doesn't seem to like the fact the the plugin returns a hostname but the underlying service was created with and IP or vice versa.

**Comment by chirag-manwani** [comment]
@Gomer05 This does seem weird as it should not matter what the Service host is which is anyways going to be overridden. 
Regardless, thanks for pointing this out. We will try to understand how and why this happens. 
Cheers!
